### ISSUE TITLE
[Errno 111] Connection refused'

### ISSUE THREAD

**Issue by arlla** [rapp-project/rapps-nao#3]
HTTPConnectionPool(host='localhost', port=9001): Max retries exceeded with url: /hop/qr_detection (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fd94cfb73d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
Call to platform finished
No QR codes were detected

Getting this error, please help.

**Comment by klpanagi** [comment]
Dear @arllab123, although the RAPP Project has been dropped due the redesign and development of a new Platform based on on SOTA Technologies (not yet publicly available), I am going to try to support you on this one.

It seems like the Platform hosting the Web and backend services is not running. The error indicates a connection error to the RAPP Platform. Please read carefully the below wiki sections on how to properly do that:
- [How can I set up the RAPP Platform in my PC](https://github.com/rapp-project/rapp-platform/wiki/How-can-I-set-up-the-RAPP-Platform-in-my-PC%3F)
- [How do I launch the RAPP Platform](https://github.com/rapp-project/rapp-platform/wiki/How-do-I-launch-the-RAPP-Platform%3F)
- [How can I see that everything is working properly](https://github.com/rapp-project/rapp-platform/wiki/How-can-I-see-that-everything-is-working-properly%3F)

**Comment by arlla** [comment]
Thank You
